@baseUrl = http://localhost:3000

# Recados
###
GET {{baseUrl}}/recados/
###
GET {{baseUrl}}/recados/
?offset=10
&limit=10
###
GET {{baseUrl}}/recados/2/
###
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": "Olá, tudo bem?",
    "deId": 1,
    "paraId": 1
}

###
PATCH  {{baseUrl}}/recados/2
Content-Type: application/json

{
    "texto": "Recado atualizado"
}

###
DELETE {{baseUrl}}/recados/1



# Pessoas
###
GET {{baseUrl}}/pessoas/
###
GET {{baseUrl}}/pessoas/
?offset=10
&limit=10
###
GET {{baseUrl}}/pessoas/2/
###
POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
    "nome": "Maria",
    "email": "maria@gmail.com",
    "password": "123456"
}

###
PATCH  {{baseUrl}}/pessoas/2
Content-Type: application/json

{
   "nome": "Maria Silva",
   "password": "654321"
}

###
DELETE {{baseUrl}}/pessoas/1